include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  strong-mode:
    implicit-dynamic: false
    implicit-casts: true

  exclude:
    - font_awesome/**
    - feature_template/**
    - packages/ferry_gen/**
    - packages/bff_chopper_gen/**
    - packages/swagger-dart-code-generator/**
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/**/*.g.dart
    - lib/gen/assets.gen.dart
    - test/**/*.mocks.dart
    - lib/**/*.freezed.dart
  plugins:
    - dart_code_metrics
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - packages/ferry_gen/**
    - packages/bff_chopper_gen/**
    - packages/swagger-dart-code-generator/**
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/**/*.g.dart
    - lib/gen/assets.gen.dart
    - test/**/*.mocks.dart
    - feature_template/**
  rules-exclude:
    - test/**
    - packages/ferry_gen/**
    - packages/bff_chopper_gen/**
    - packages/swagger-dart-code-generator/**
    - integration_test/**
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/**/*.g.dart
    - lib/gen/assets.gen.dart
    - feature_template/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
linter:
  rules:
    always_specify_types: true
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    one_member_abstracts: false
    public_member_api_docs: false
