name: test_example
description: Meeh

dependencies:
  flutter_test:
    sdk: flutter
  
dev_dependencies:
  very_good_analysis: ^4.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter:
  uses-material-design: true

